### ISSUE TITLE
double jeopardy seems to not working

### ISSUE THREAD

**Issue by trockenasche** [FSI-HochschuleTrier/hacker-jeopardy#1]
Thanks for this game, it's really cool and it's looks great and nerdy.

Unfortunately it seems that double jeopardy doesn't work. I got the screen with an input but it doesn't matter what I try to put in, the OK Button nor enter doesn't do anything. The only way to get rid of it, is to click to any other question. But doing so, no buzzer get recognised and only pressing "wrong answer" let me continue.

**Comment by miko007** [comment]
unfortunately, the controls are not documented. when the "double jeopardy" dialogue is popping up, you have to select the player who chooses the amount to put in by pressing the left or right keys.

**Comment by trockenasche** [comment]
Thanks for the hint, it's working!
